spring:
  ##############datasource
  datasource:
    url: jdbc:mysql://localhost:3306/sunrise?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid.initial-size: 1
    druid.max-active: 20
    druid.min-idle: 1
  ##############redis
  redis:
    host: localhost
    password: test
    database: 0



##############dubbo
dubbo:
  application:
    id: message-provider
    name: message-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: message-registry
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.alibaba.boot.dubbo.demo.provider.service
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool










